---
  - name: Check reboot privilege
    command: sudo -l
    args:
      warn: false
    register: result_sudo
    changed_when: false

  - debug: msg="{{ result_sudo.stdout }}"
  - fail: msg="Reboot privilege missing!"
    #when: ("(ALL) ALL" not in result_sudo.stdout) or
  #      ("(ALL) NOPASSWD" not in result_sudo.stdout) or
  #        ("reboot" not in result_sudo.stdout)

    when: ("(ALL) ALL" not in result_sudo.stdout) or
          ("reboot" not in result_sudo.stdout)                    
