---
  - name: "Check reboot privilege"
    command: sudo -l
    args:
      warn: false
    register: result_sudo
    become: yes
  - debug: msg="{{ result_sudo.stdout }}"
  - fail: msg="Reboot privilege missing!"
    when: not(result_sudo.stdout.find('ALL') != -1) #or
          #not(result_sudo.stdout.find('(ALL) NOPASSWD":" ALL') != -1)
