---
  - name: "Stopping {{ service_to_restart }}"
    service: 
      name: "{{ service_to_restart }}"
      state: stopped

  - name: "Installing updates using yum"
    yum:
      name: "*"
      state: latest
      update_only: "yes"
    register: update_result

  - name: "Printing yum update results"
    debug:
      msg: "{{ update_result.results }}"
    
  - block:
      - name: "Reboot if there was a change"
        shell: "sleep 5 && /usr/sbin/reboot"
        async: 1
        poll: 0

      - name: "Wait for the reboot"
        wait_for_connection:
          connect_timeout: 20
          sleep: 5
          delay: 5
          timeout: 300
    when: 
      - update_result is changed
      - ansible_uptime_seconds > 86400

  - name: "Check server uptime"
    shell: "uptime | awk '{print $3,$4}'"
    register: uptime

  - name: "Print uptime"
    debug:
      msg: "{{ uptime.stdout }}"

  - name: "Starting {{ service_to_restart }}"
    service: 
      name: "{{ service_to_restart }}"
      state: started

  - name: "Make sure HTTP is running before proceeding"
    wait_for: 
      host: 0.0.0.0 
      port: 80 
      delay: 3 
      timeout: 300


### For Testing purposes 
  - name: Pinging from Ansible server to {{ inventory_hostname }}
    shell: hostname && ping -c 3 {{ ansible_default_ipv4.address }}
    when: inventory_hostname == ansible_play_hosts[0]
    delegate_to: localhost 

  - name: Echo some variable
    shell: echo "{{ this_var }}" | tee /tmp/some_var_file

  - debug: msg="Cheking THIS_var is Hello"
    when: this_var == "Hello"
  - fail: msg="Cheking THIS_var is not Hello"
    when: this_var != "Hello"

